// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTltlQhN0qCMVnu3LcD7SiP0k3L_pcUP8',
    appId: '1:628514376564:web:474a24b4ccad9e6cb3fa21',
    messagingSenderId: '628514376564',
    projectId: 'damaged303-21e1e',
    authDomain: 'damaged303-21e1e.firebaseapp.com',
    storageBucket: 'damaged303-21e1e.firebasestorage.app',
    measurementId: 'G-1YD6WSSPWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOpMuhfx-mUWuKAgGjOTUOwgdkjbbBDdc',
    appId: '1:628514376564:android:77152a90ff570ec1b3fa21',
    messagingSenderId: '628514376564',
    projectId: 'damaged303-21e1e',
    storageBucket: 'damaged303-21e1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyyfGLeEOyFl3ChukUG1lpfy0W3rWetPA',
    appId: '1:628514376564:ios:74a309f5d6a8498eb3fa21',
    messagingSenderId: '628514376564',
    projectId: 'damaged303-21e1e',
    storageBucket: 'damaged303-21e1e.firebasestorage.app',
    iosBundleId: 'com.example.damaged303',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyyfGLeEOyFl3ChukUG1lpfy0W3rWetPA',
    appId: '1:628514376564:ios:74a309f5d6a8498eb3fa21',
    messagingSenderId: '628514376564',
    projectId: 'damaged303-21e1e',
    storageBucket: 'damaged303-21e1e.firebasestorage.app',
    iosBundleId: 'com.example.damaged303',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTltlQhN0qCMVnu3LcD7SiP0k3L_pcUP8',
    appId: '1:628514376564:web:3ee7bf28b5de143ab3fa21',
    messagingSenderId: '628514376564',
    projectId: 'damaged303-21e1e',
    authDomain: 'damaged303-21e1e.firebaseapp.com',
    storageBucket: 'damaged303-21e1e.firebasestorage.app',
    measurementId: 'G-X394EGXQ63',
  );
}
